### ISSUE TITLE
Entity  (<class 'custom_components.xiaomi_miot.light.MiotLightSubEntity'>) is using deprecated supported features values.

### ISSUE THREAD

**Issue by M0Rf30** [al-one/hass-xiaomi-miot#1497]
Hi and thanks for this wonderful project
Hereby I report some deprecations.

```
Entity light.*_*_indicator_light (<class 'custom_components.xiaomi_miot.light.MiotLightSubEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color mode
```

Hope to do something useful.
Regards

**Comment by dogmatic69** [comment]
I have 3500+ lines of entries like this in the logs

```
2024-01-16 00:17:44.501 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_AQI was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.AQI instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.511 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_BATTERY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.BATTERY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.522 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_CO was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.CO instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.532 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_CO2 was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.CO2 instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.542 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_CURRENT was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.CURRENT instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.553 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_DATE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.DATE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.563 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_ENERGY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ENERGY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.573 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_FREQUENCY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.FREQUENCY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.584 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_GAS was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.GAS instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.594 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_HUMIDITY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.HUMIDITY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.605 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_ILLUMINANCE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ILLUMINANCE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.615 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_MONETARY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.MONETARY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.626 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_NITROGEN_DIOXIDE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.NITROGEN_DIOXIDE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.637 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_NITROGEN_MONOXIDE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.NITROGEN_MONOXIDE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.647 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_NITROUS_OXIDE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.NITROUS_OXIDE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.658 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_OZONE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.OZONE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.669 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_PM1 was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.PM1 instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.680 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_PM10 was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.PM10 instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.691 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_PM25 was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.PM25 instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.702 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_POWER_FACTOR was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.POWER_FACTOR instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.712 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_POWER was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.POWER instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.723 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_PRESSURE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.PRESSURE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.734 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_SIGNAL_STRENGTH was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.SIGNAL_STRENGTH instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
2024-01-16 00:17:44.745 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_SULPHUR_DIOXIDE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.SULPHUR_DIOXIDE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
```

**Comment by M0Rf30** [comment]
> I have 3500+ lines of entries like this in the logs
> 
> ```
> 2024-01-16 00:17:44.501 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_AQI was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.AQI instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.511 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_BATTERY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.BATTERY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.522 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_CO was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.CO instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.532 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_CO2 was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.CO2 instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.542 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_CURRENT was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.CURRENT instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.553 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_DATE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.DATE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.563 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_ENERGY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ENERGY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.573 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_FREQUENCY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.FREQUENCY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.584 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_GAS was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.GAS instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.594 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_HUMIDITY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.HUMIDITY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.605 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_ILLUMINANCE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.ILLUMINANCE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.615 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_MONETARY was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.MONETARY instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.626 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_NITROGEN_DIOXIDE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.NITROGEN_DIOXIDE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.637 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_NITROGEN_MONOXIDE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.NITROGEN_MONOXIDE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.647 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_NITROUS_OXIDE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.NITROUS_OXIDE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.658 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_OZONE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.OZONE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.669 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_PM1 was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.PM1 instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.680 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_PM10 was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.PM10 instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.691 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_PM25 was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.PM25 instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.702 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_POWER_FACTOR was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.POWER_FACTOR instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.712 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_POWER was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.POWER instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.723 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_PRESSURE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.PRESSURE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.734 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_SIGNAL_STRENGTH was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.SIGNAL_STRENGTH instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> 2024-01-16 00:17:44.745 WARNING (MainThread) [homeassistant.const] DEVICE_CLASS_SULPHUR_DIOXIDE was used from xiaomi_miot, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.SULPHUR_DIOXIDE instead, please create a bug report at https://github.com/al-one/hass-xiaomi-miot/issues
> ```

They are already fixed in master if you are using latest stable tag.
This warning instead seems to be the only one already present in latest commit

**Comment by dogmatic69** [comment]
I'm using the latest available on hacs

**Comment by hmmbob** [comment]
Quite confident that this is fixed by #1485, but that hasn't been part of a release yet.

**Comment by h3nrytan** [comment]
> Quite confident that this is fixed by #1485, but that hasn't been part of a release yet.

Tried with the latest fixed. that one error still persist:-

Entity light.*_*_indicator_light (<class 'custom_components.xiaomi_miot.light.MiotLightSubEntity'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <LightEntityFeature: 0> and color mode

Thanks for looking into it
