### ISSUE TITLE
Setup failed for custom integration 'xiaomi_miot': Unable to import component: No module named 'imp'

### ISSUE THREAD

**Issue by ffsszzll** [al-one/hass-xiaomi-miot#1526]
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 2024年2月8日 23:51:12 (1 occurrences)
Last logged: 2024年2月8日 23:51:12

Setup failed for custom integration 'xiaomi_miot': Unable to import component: No module named 'imp'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miot/__init__.py", line 32, in <module>
    from miio import (
  File "/usr/local/lib/python3.12/site-packages/miio/__init__.py", line 12, in <module>
    from miio.device import Device, DeviceStatus  # isort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 13, in <module>
    from .miioprotocol import MiIOProtocol
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 13, in <module>
    import construct
  File "/usr/local/lib/python3.12/site-packages/construct/__init__.py", line 22, in <module>
    from construct.core import *
  File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in <module>
    import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'

**Comment by simongrech** [comment]
Same issue...

**Comment by nouocc** [comment]
同样的问题...

**Comment by Herriaan** [comment]
Same issue here as well

**Comment by Tamago2000** [comment]
Same issue here

**Comment by neonomc** [comment]
Same here

**Comment by balabaec** [comment]
Same problem after update

**Comment by pcrlbnne** [comment]
Same issue here

**Comment by vapustovoyt** [comment]
Works after upgrade to 2024.2.1

**Comment by neonomc** [comment]
> Works after upgrade to 2024.2.1

For me not

**Comment by shadowbane** [comment]
Not working for me. Home Assistant 2024.2.1

```
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 00:32:18 (1 occurrences)
Last logged: 00:32:18

Setup failed for custom integration 'xiaomi_miot': Unable to import component: No module named 'imp'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miot/__init__.py", line 32, in <module>
    from miio import (
  File "/usr/local/lib/python3.12/site-packages/miio/__init__.py", line 12, in <module>
    from miio.device import Device, DeviceStatus  # isort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 13, in <module>
    from .miioprotocol import MiIOProtocol
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 13, in <module>
    import construct
  File "/usr/local/lib/python3.12/site-packages/construct/__init__.py", line 22, in <module>
    from construct.core import *
  File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in <module>
    import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'

```

**Comment by mbu147** [comment]
The problem is caused by a Python upgrade (to 3.12).
https://www.home-assistant.io/blog/2024/02/07/release-20242/#shipping-on-a-new-python-version

**Comment by imdyu** [comment]
Logger: homeassistant.setup
Source: setup.py:251
First occurred: 13:21:31 (1 occurrences)
Last logged: 13:21:31

Setup failed for custom integration 'xiaomi_miot': Unable to import component: No module named 'imp'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miot/__init__.py", line 32, in <module>
    from miio import (
  File "/usr/local/lib/python3.12/site-packages/miio/__init__.py", line 12, in <module>
    from miio.device import Device, DeviceStatus  # isort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 13, in <module>
    from .miioprotocol import MiIOProtocol
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 13, in <module>
    import construct
  File "/usr/local/lib/python3.12/site-packages/construct/__init__.py", line 22, in <module>
    from construct.core import *
  File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in <module>
    import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'

**Comment by Sergmasharov** [comment]
same issue

**Comment by Cedary** [comment]
更新HA后不能用的, 应该是2024.2版本的HA更新了python, 如果急用可以回滚HA到2024.2之前的版本试试 (做好备份

**Comment by ffsszzll** [comment]
谢谢！已经通过恢复备份修复。



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 12, 2024 12:07 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [al-one/hass-xiaomi-miot] Setup failed for custom integration'xiaomi_miot': Unable to import component: No module named 'imp' (Issue #1526)




 
更新HA后不能用的, 应该是2024.2版本的HA更新了python, 如果急用可以回滚HA到2024.2之前的版本试试 (做好备份

**Comment by btbxbob** [comment]
run command:
```
pip install construct --upgrade
```
can solve the problem.

**Comment by ffsszzll** [comment]
Thanks!



---Original---
From: "Bob ***@***.***&gt;
Date: Tue, Feb 13, 2024 02:59 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [al-one/hass-xiaomi-miot] Setup failed for custom integration'xiaomi_miot': Unable to import component: No module named 'imp' (Issue #1526)




 
run command:
 pip install construct --upgrade  
can solve the problem.

**Comment by Lemonadel** [comment]
Same. Stopped working after simple restart - HAOS update was few days ago to 2024.2.1, crazy

**Comment by exeljb** [comment]
I too am seeing this error.  Integration fails to load after updating hassos.  Regretting that update now.

**Comment by balabaec** [comment]
> run command:
> 
> ```
> pip install construct --upgrade
> ```
> 
> can solve the problem.
> 
> see #[construct/construct@a2d5c24](https://github.com/construct/construct/commit/a2d5c249b7039b70becbece4cc9c7bfa9e682f00)

Where?

**Comment by Lemonadel** [comment]
Seems to be fixed with todays HAOS Core update: 2024.2.2

btw how someone using HAOS can run pip if it’s not installed ? Is there some kind of backdoor to install additional packages ?

![IMG_3288](https://github.com/al-one/hass-xiaomi-miot/assets/43881989/5e1f2387-3244-40a3-b3be-fc551ca059e1)

**Comment by exeljb** [comment]
I’ve updated to 2024.2.2 as well and the integration loaded successfully now.

**Comment by Sergmasharov** [comment]
Confirmed, 2024.2.2 solve the problem.

**Comment by mehmetaktas** [comment]
Same issue...
<img width="665" alt="image" src="https://github.com/al-one/hass-xiaomi-miot/assets/2642542/267154c3-ac07-434d-95ce-63a42f343290">

**Comment by EvgenaNet** [comment]
Same issue.


![Screenshot_2024-02-18-08-48-19-40_c3a231c25ed346e59462e84656a70e50](https://github.com/al-one/hass-xiaomi-miot/assets/60606013/516270d7-ac5e-4924-9825-f1c834c06ad7)

**Comment by btbxbob** [comment]
> Seems to be fixed with todays HAOS Core update: 2024.2.2
> 
> btw how someone using HAOS can run pip if it’s not installed ? Is there some kind of backdoor to install additional packages ?
> 
> ![IMG_3288](https://private-user-images.githubusercontent.com/43881989/305583530-5e1f2387-3244-40a3-b3be-fc551ca059e1.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNTEyMzQsIm5iZiI6MTcwODI1MDkzNCwicGF0aCI6Ii80Mzg4MTk4OS8zMDU1ODM1MzAtNWUxZjIzODctMzI0NC00MGEzLWIzYmUtZmM1NTFjYTA1OWUxLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxMDA4NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZWZjNDAyYWQzNzFjYzAyZGI3NTg3NzllOWU1NTFhZjQ0NmU5Y2MwZmY4ODE1YjFhMjEyNGYxMzMxYzllOWM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5YrnqRkbxXvOyDeQcsm4AuEGqfgfDvWO6E7qnZzfSkE)

you can see here:
https://www.home-assistant.io/faq/pip3/

**Comment by btbxbob** [comment]
> > run command:
> > ```
> > pip install construct --upgrade
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > can solve the problem.
> > see #[construct/construct@a2d5c24](https://github.com/construct/construct/commit/a2d5c249b7039b70becbece4cc9c7bfa9e682f00)
> 
> Where should I run it?

in the console.

**Comment by emredemirhan** [comment]
Guys I have found how to solve this problem. At least it worked for me. 

Here are the steps : 

First we need to get into the docker container of homeasisstnant, trying to write commands from terminal directly is not going to work. 

1. Install "Advanced SSH & Web Terminal" addon for home assistant to be able to react the terminal.
2. execute "docker ps" command to be able to see running containers.
3. Find the container id with image : ghcr.io/home-assistant/raspberrypi5-64-homeassistant:2024.2.2, your image may be different cause I'm running my ha on raspberry pi 5 but basically we need to find the id of the container for home assistant docker container
4. execute    "docker exec -it <container_id> /bin/bash" replace container_id with the id that you have found in the previous step.
5.  You're in the container now. You can try to run "pip install construct --upgrade" the latest version uses importlib instead of imp. 
6. But in my case the problem was that contruct package was still using an old version, so I had to remove the __pycache__ folder for construct
7. navigate to the construct package directory by : cd /usr/local/lib/python3.12/site-packages/construct/
8.  execute "rm -rf __pycache__" this will remove the __pycache__ folder, don't worry it will be regenerated after you restart the home assistant

reboot the server and you're done. ;)

**Comment by ffsszzll** [comment]
Thanks!



---Original---
From: "Emre ***@***.***&gt;
Date: Mon, Feb 19, 2024 01:52 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [al-one/hass-xiaomi-miot] Setup failed for custom integration'xiaomi_miot': Unable to import component: No module named 'imp' (Issue #1526)




 
Guys I have found how to solve this problem. At least it worked for me.
 
Here are the steps :
 
First we need to get into the docker container of homeasisstnant, trying to write commands from terminal directly is not going to work.
  
Install "Advanced SSH &amp; Web Terminal" addon for home assistant to be able to react the terminal.
 
execute "docker ps" command to be able to see running containers.
 
Find the container id with image : ghcr.io/home-assistant/raspberrypi5-64-homeassistant:2024.2.2, your image may be different cause I'm running my ha on raspberry pi 5 but basically we need to find the id of the container for home assistant docker container
 
execute    "docker exec -it <container_id&gt; /bin/bash" replace container_id with the id that you have found in the previous step.
 
You're in the container now. You can try to run "pip install construct --upgrade" the latest version uses importlib instead of imp.
 
But in my case the problem was that contruct package was still using an old version, so I had to remove the pycache folder for construct
 
navigate to the construct package directory by : cd /usr/local/lib/python3.12/site-packages/construct/
 
execute "rm -rf pycache" this will remove the pycache folder, don't worry it will be regenerated after you restart the home assistant
  
reboot the server and you're done. ;)

**Comment by dumbodumbos** [comment]
In version 2024.2.2 it works until the first reboot

**Comment by anglrus** [comment]
For me does not work in version 2024.2.2.

**Comment by achillecalegari** [comment]
> > > run command:
> > > ```
> > > pip install construct --upgrade
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > can solve the problem.
> > > see #[construct/construct@a2d5c24](https://github.com/construct/construct/commit/a2d5c249b7039b70becbece4cc9c7bfa9e682f00)
> > 
> > 
> > Where should I run it?
> 
> in the console.

Tried but doesn't work still

**Comment by theodorx7** [comment]
Doesn't work on version HA 2024.2.2, the same error appears.

Logger: homeassistant.setup
Source: setup.py:251
First occurred: 18:29:51 (1 occurrences)
Last logged: 18:29:51

Setup failed for custom integration 'xiaomi_miot': Unable to import component: No module named 'imp'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 251, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 827, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miot/__init__.py", line 32, in <module>
    from miio import (
  File "/usr/local/lib/python3.12/site-packages/miio/__init__.py", line 12, in <module>
    from miio.device import Device, DeviceStatus  # isort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 13, in <module>
    from .miioprotocol import MiIOProtocol
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 13, in <module>
    import construct
  File "/usr/local/lib/python3.12/site-packages/construct/__init__.py", line 22, in <module>
    from construct.core import *
  File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in <module>
    import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'

**Comment by neonomc** [comment]
Guys, check if you have newest release of this integration. Mine was sideloaded directly in custom_cpomponents, or strangly dissapear in hacs, and I don't update it until 2022!

After adding it from HACS and upgrading integration all works. 

OFC i put this `
![image](https://github.com/al-one/hass-xiaomi-miot/assets/118989505/95347399-bcd4-444e-ba39-a2736c12e372)
`
in ssh terminal addon from HACS

**Comment by achillecalegari** [comment]
> Guys, check if you have newest release of this integration. Mine was sideloaded directly in custom_cpomponents, or strangly dissapear in hacs, and I don't update it until 2022!
> 
> After adding it from HACS and upgrading integration all works.
> 
> OFC i put this `pip install construct --upgrade` in ssh terminal addon from HACS
> 
> EDIT - bad link

I get the following error, and nothing is fixed after:

→ ~ pip install construct --upgrade
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting construct
Downloading https://wheels.home-assistant.io/musllinux-index/construct-2.10.70-py3-none-any-whl (63 kB)
63.0/63.0 kB 89.5 MB/s eta
0:00:00
Installing collected packages: construct
Successfully installed construct-2.10.70
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip. pypa. io/warnings/venv

**Comment by oallain** [comment]
Hello,

It dosn't work for me too.
```bash
$ pip install construct --upgrade
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Requirement already satisfied: construct in /usr/local/lib/python3.12/site-packages (2.10.56)
Collecting construct
  Downloading https://wheels.home-assistant.io/musllinux-index/construct-2.10.70-py3-none-any.whl (63 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 518.3 kB/s eta 0:00:00
Installing collected packages: construct
  Attempting uninstall: construct
    Found existing installation: construct 2.10.56
    Uninstalling construct-2.10.56:
      Successfully uninstalled construct-2.10.56
Successfully installed construct-2.10.70
```

![image](https://github.com/al-one/hass-xiaomi-miot/assets/6593252/109525af-3e57-4cb3-92df-d37d74264d41)

I've restart my HA too.
And i have this error : 

![image](https://github.com/al-one/hass-xiaomi-miot/assets/6593252/fcc423c7-cda3-4d8c-9224-0291023cbc7b)

Have you another idea ?

**Comment by balabaec** [comment]
> > > run command:
> > > ```
> > > pip install construct --upgrade
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > can solve the problem.
> > > see #[construct/construct@a2d5c24](https://github.com/construct/construct/commit/a2d5c249b7039b70becbece4cc9c7bfa9e682f00)
> > 
> > 
> > Where should I run it?
> 
> in the console.

I ran it at my device console. The upgrade happened, Then I rebooted my device, but Miot Auto still not working

**Comment by btbxbob** [comment]
> Hello,
> 
> 
> 
> It dosn't work for me too.
> 
> ```bash
> 
> $ pip install construct --upgrade
> 
> Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
> 
> Requirement already satisfied: construct in /usr/local/lib/python3.12/site-packages (2.10.56)
> 
> Collecting construct
> 
>   Downloading https://wheels.home-assistant.io/musllinux-index/construct-2.10.70-py3-none-any.whl (63 kB)
> 
>      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.0/63.0 kB 518.3 kB/s eta 0:00:00
> 
> Installing collected packages: construct
> 
>   Attempting uninstall: construct
> 
>     Found existing installation: construct 2.10.56
> 
>     Uninstalling construct-2.10.56:
> 
>       Successfully uninstalled construct-2.10.56
> 
> Successfully installed construct-2.10.70
> 
> ```
> 
> 
> 
> ![image](https://github.com/al-one/hass-xiaomi-miot/assets/6593252/109525af-3e57-4cb3-92df-d37d74264d41)
> 
> 
> 
> I've restart my HA too.
> 
> And i have this error : 
> 
> 
> 
> ![image](https://github.com/al-one/hass-xiaomi-miot/assets/6593252/fcc423c7-cda3-4d8c-9224-0291023cbc7b)
> 
> 
> 
> Logs : 
> 
> 
> 
> ![image](https://github.com/al-one/hass-xiaomi-miot/assets/6593252/9f0065d7-a7fa-4716-a34b-aa7acac26bc5)
> 
> 
> 
> 
> 
> Have you another idea ?

Strange, in the last few lines of your error log, it shows the "construct" library is not upgraded at all.
Maybe you should find the specific python to upgrade it.

**Comment by dumbodumbos** [comment]
In version v0.7.16 it also does not work. Dies on first reboot

**Comment by al-one** [comment]
Try master branch.

**Comment by dumbodumbos** [comment]
On the master version as well. I noticed the following, if I rebooted and the integration fell into error, you restart the software again and it happens that it starts normally

**Comment by oallain** [comment]
> Try master branch.

I've try with with HACS but i got 
`ERROR (MainThread) [custom_components.hacs] <Integration al-one/hass-xiaomi-miot> Failed to download https://github.com/al-one/hass-xiaomi-miot/releases/download/master/xiaomi_miot.zip`

**Comment by oallain** [comment]
Hello @al-one  

I made a PR, becose we need to upgrade construct lib to fix it.
It's work fine for me with it 😄

**Comment by balabaec** [comment]
It seems to be working correctly after updating to 0.7.16

**Comment by mehmetaktascs** [comment]
> It seems to be working correctly after updating to 0.7.16

How is the updating process carried out?

**Comment by mehmetaktas** [comment]
> It seems to be working correctly after updating to 0.7.16

How is the updating process carried out?

**Comment by theodorx7** [comment]
> It seems to be working correctly after updating to 0.7.16

Version 0.7.16, as well as the master branch, still generate an error.  Nothing has been fixed.

**Comment by oallain** [comment]
> > It seems to be working correctly after updating to 0.7.16
> 
> Version 0.7.16, as well as the master branch, still generate an error. Nothing has been fixed.

Fix is here https://github.com/al-one/hass-xiaomi-miot/pull/1561

You can manually edit your file and restart HA.

**Comment by ARCL01** [comment]
> > > It seems to be working correctly after updating to 0.7.16
> > 
> > 
> > Version 0.7.16, as well as the master branch, still generate an error. Nothing has been fixed.
> 
> Fix is here #1561
> 
> You can manually edit your file and restart HA.

This one worked like a charm, thanks a lot.

**Comment by sulliwane** [comment]
Hi all and @oallain,

I still experience this issue in my HA:
![image](https://github.com/al-one/hass-xiaomi-miot/assets/1733686/048e4bc7-892a-413c-9bab-0a28ce77f4d8)


```
Logger: homeassistant.setup
Source: setup.py:316
First occurred: April 7, 2024 at 20:12:04 (2 occurrences)
Last logged: April 7, 2024 at 20:12:04

Setup failed for custom integration 'xiaomi_miot': Unable to import component: No module named 'imp'
Setup failed for custom integration 'aqara_gateway': Unable to import component: No module named 'imp'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 979, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miot/__init__.py", line 32, in <module>
    from miio import (
  File "/usr/local/lib/python3.12/site-packages/miio/__init__.py", line 12, in <module>
    from miio.device import Device, DeviceStatus  # isort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 13, in <module>
    from .miioprotocol import MiIOProtocol
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 13, in <module>
    import construct
  File "/usr/local/lib/python3.12/site-packages/construct/__init__.py", line 22, in <module>
    from construct.core import *
  File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in <module>
    import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 316, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 997, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 989, in async_get_component
    comp = self._get_component()
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1037, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/xiaomi_miot/__init__.py", line 32, in <module>
    from miio import (
  File "/usr/local/lib/python3.12/site-packages/miio/__init__.py", line 12, in <module>
    from miio.device import Device, DeviceStatus  # isort: skip
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/miio/device.py", line 13, in <module>
    from .miioprotocol import MiIOProtocol
  File "/usr/local/lib/python3.12/site-packages/miio/miioprotocol.py", line 13, in <module>
    import construct
  File "/usr/local/lib/python3.12/site-packages/construct/__init__.py", line 22, in <module>
    from construct.core import *
  File "/usr/local/lib/python3.12/site-packages/construct/core.py", line 3, in <module>
    import struct, io, binascii, itertools, collections, pickle, sys, os, tempfile, hashlib, importlib, imp
ModuleNotFoundError: No module named 'imp'
```
Here is my HA version:
![Screenshot from 2024-04-08 11-30-43](https://github.com/al-one/hass-xiaomi-miot/assets/1733686/c42379e0-dda2-44fe-bf2b-7ec38f44189e)

What I don't understand is what's the difference between this integration (https://www.home-assistant.io/integrations/xiaomi_miio / https://github.com/home-assistant/core/tree/dev/homeassistant/components/xiaomi_miio) and this integration (https://github.com/al-one/hass-xiaomi-miot). Are they the same? 

or should I report my issue in another github repository...

THanks a lot for your help!
