### ISSUE TITLE
MJSXJ02HL (isa.camera.hlc6) Error: cannot import name 'COLOR_MODE_ONOFF'

### ISSUE THREAD

**Issue by deneraraujo** [al-one/hass-xiaomi-miot#155]
Hi.
I'm trying to integrate my MJSXJ02HL (isa.camera.hlc6) camera to HA but I getting some issues.

- ## First, I got this message:
![](https://drive.google.com/uc?export=view&id=11hfpo8rAmsX16qPWPXovtkkoFcmebNcN)

The logs:

```
Logger: homeassistant.helpers.entity
Source: custom_components/xiaomi_miot/light.py:6
First occurred: 5:25:15 PM (1 occurrences)
Last logged: 5:25:15 PM
Update for camera.camera_de_seguranca_residencial_1080p_mi_suporte_magnetico_camera_control fails

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 278, in async_update_ha_state
    await self.async_device_update()
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 474, in async_device_update
    raise exc
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miot/camera.py", line 131, in async_update
    await super().async_update()
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miot/__init__.py", line 941, in async_update
    domain='sensor',
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miot/__init__.py", line 1166, in _update_sub_entities
    from .light import MiotLightSubEntity
  File "/home/homeassistant/.homeassistant/custom_components/xiaomi_miot/light.py", line 6, in <module>
    from homeassistant.components.light import (
ImportError: cannot import name 'COLOR_MODE_ONOFF' from 'homeassistant.components.light' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/light/__init__.py)
```
```


Logger: homeassistant.setup
Source: setup.py:280
First occurred: 5:24:11 PM (2 occurrences)
Last logged: 5:24:12 PM

    Unable to prepare setup for platform xiaomi_miot.cover: Platform not found (cannot import name 'COLOR_MODE_ONOFF' from 'homeassistant.components.light' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/light/__init__.py)).
    Unable to prepare setup for platform xiaomi_miot.light: Platform not found (cannot import name 'COLOR_MODE_ONOFF' from 'homeassistant.components.light' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/light/__init__.py)).


```

- ## So I edited the **light.py** file, and commented the lines 17-20 and 89-99, and restarted the HA:
(After comment COLOR_MODE_ONOFF, I got errors on COLOR_MODE_BRIGHTNESS, COLOR_MODE_COLOR_TEMP and COLOR_MODE_HS too. So I I had to comment them all.)

![](https://drive.google.com/uc?export=view&id=1BN2A0sfG4_HcwdM_kE3ygGYs08C5-flh)
![](https://drive.google.com/uc?export=view&id=11kyooHwZfNbIhj_x0qzH3sn7RGy84343)

- ## The errors stopped and I started to receive notifications from Mi Home app on my phone:
![](https://drive.google.com/uc?export=view&id=1SZ3Cr7lEwIfipconH2OtmjRQNGhtjkPo)

- ## But I still couldn't get the stream:
![](https://drive.google.com/uc?export=view&id=1BqqYUpBeMsZCQPSAUiF5DcqrLvS4WG86)

- ## I tried to set miot_cloud to "true" and restart HA:
![](https://drive.google.com/uc?export=view&id=19FqYFhXwMLjdLua9xRRtstYUByUT1xry)
![](https://drive.google.com/uc?export=view&id=1F6XvbNhZCb6-_gJHpBMgWt5luE7Lvlxo)

- ## But no stream:
![](https://drive.google.com/uc?export=view&id=1BqqYUpBeMsZCQPSAUiF5DcqrLvS4WG86)

Could you please help me?

Best regards.

**Comment by al-one** [comment]
`Error: cannot import name 'COLOR_MODE_ONOFF'` was fixed in commit: https://github.com/al-one/hass-xiaomi-miot/commit/48841d8d657f3b5bf4ffca2ea3c0acec838046c6.
You need upgrade the component to `master` or upgrade HA to `v2021.4+`.

**Comment by deneraraujo** [comment]
> 
> 
> `Error: cannot import name 'COLOR_MODE_ONOFF'` was fixed in commit: [48841d8](https://github.com/al-one/hass-xiaomi-miot/commit/48841d8d657f3b5bf4ffca2ea3c0acec838046c6).
> You need upgrade the component to `master` or upgrade HA to `v2021.4+`.

Thank you!

This fixed the COLOR_MODE_ONOFF, COLOR_MODE_BRIGHTNESS, COLOR_MODE_COLOR_TEMP, COLOR_MODE_HS errors.



But I still cannot get the stream:

![](https://drive.google.com/uc?export=view&id=1dqKxaKVls9zzXIwlLLkE1k-JRZTpKLfU)
