### ISSUE TITLE
Devices can't be configures (MIOT spec down)

### ISSUE THREAD

**Issue by nicoodeimos** [al-one/hass-xiaomi-miot#2518]
### Device model / 设备型号

Any

### Component version / 插件版本

1.0.19

### HA core version / HA版本

2025..5.2

### Integrated mode / 集成方式

Automatic (自动模式)

### The problem / 问题详情

It seems that https://home.miot-spec.com is down (error 500) and that devices won't configure now.

### Entity attributes / 实体属性

```yaml
N/A
```

**Comment by meowwwwww95** [comment]
Me too. Looking forward to the service being restored as soon as possible.

**Comment by Apricityx** [comment]
same.

**Comment by nicoodeimos** [comment]
@al-one any info on this? This completely breaks the plugin. Thanks.

**Comment by meowwwwww95** [comment]
> [@al-one](https://github.com/al-one) any info on this? This completely breaks the plugin. Thanks.
It seems that this problem has been fixed, but the reason is unknown. I think we should switch data source to official source MIoT or backup the data.

**Comment by nicoodeimos** [comment]
The specs are live again, but the plugin still cannot configure my devices. Anyone else?

**Comment by al-one** [comment]
This website (`home.miot-spec.com`) will not affect your device. This integration retrieves data from Xiaomi's official spec website (`miot-spec.org`), not from this website.
