### ISSUE TITLE
DE server - Unable to get devices

### ISSUE THREAD

**Issue by Wh1terat** [al-one/hass-xiaomi-miot#345]
Something has changed with auth to DE server (maybe others) but not CN.

Unable to get devices or tokens, still works in MiHome and CN server still working with integration.

**Comment by TheLordVader** [comment]
Yes, I can confirm this issue as well. Devices unavailable.

**Comment by neliets** [comment]
I can also confirm - no devices are found. For me, even if I select China server, still finds none. Mi home everything is working and present.

**Comment by Zeunas** [comment]
Same as above with EU, only CN seems to be working

**Comment by RPSouto** [comment]
Same here. Only Mi Home is working since yesterday.

**Comment by raptr55** [comment]
Same for me. Only mi Home Is working. Not only vacuums but cameras has same problem

**Comment by balbulator** [comment]
I confirm, I have the same thing, the server is Europe

**Comment by al-one** [comment]
Are there any related logs ?

**Comment by raptr55** [comment]
> Are there any related logs ?

Got xiaomi cloud devices for xxxx@xxx.xxx failed: {'code': 0, 'message': 'auth err'}

**Comment by Lebedevandrey25** [comment]
Same with get token program, wrote everything correctly(checked twice) and it does not letting log in in Europe. Think that Xiaomi changed something with authorization or maybe it's a glitch with mi servers.

**Comment by kennetjuh** [comment]
I'm having the same issue, i don't think it's related to this intergration. the token_extractor is also not able to connect to the europe (de) server.

swapping to the cn server might be a quick fix for now.

**Comment by No-Smart** [comment]
I have the same problem 😕

**Comment by al-one** [comment]
Does the same problem exist in HA's built-in component [xiaomi_miio](https://www.home-assistant.io/integrations/xiaomi_miio) ?

**Comment by balbulator** [comment]
Authorization and connection from the phone through MiHome passes without problems, but with Home Assistant in no way

**Comment by balbulator** [comment]
> Does the same problem exist in HA's built-in component [xiaomi_miio](https://www.home-assistant.io/integrations/xiaomi_miio) ?

No

**Comment by raptr55** [comment]
> Does the same problem exist in HA's built-in component [xiaomi_miio](https://www.home-assistant.io/integrations/xiaomi_miio) ?

Bult-in component work, my roborock vacuum Is visibile and its working

**Comment by kennetjuh** [comment]
> Does the same problem exist in HA's built-in component [xiaomi_miio](https://www.home-assistant.io/integrations/xiaomi_miio) ?

For me it also fails connecting to the 'de' server. unknown error. when i setup the integration for the 'cn' server i get no devices as expected

**Comment by RPSouto** [comment]
Tested two more Integrations with same results.

Only DE server with problems

**Comment by rezmus** [comment]
@al-one they force rc4 on de region since yesterday ;d you may want to enable it by default, because all other cloud will proabably follow soon.

**Comment by KitHubek** [comment]
the same problem here with DE serv. **Unknown error occurred**
Xiaomi app (android and ios too) working ok

![unknow error occurreds](https://user-images.githubusercontent.com/91805313/147871755-641f495d-516a-49dc-9afe-10164cf5fc61.jpg)

**Comment by rezmus** [comment]
to use rc4 by default try to change crypt=False to crypt=True in core/xiaomi_cloud.py

**Comment by al-one** [comment]
> to use rc4 by default try to change crypt=False to crypt=True in core/xiaomi_cloud.py

Does it work for you ?

**Comment by rezmus** [comment]
i dont use HA or know python, so cant check, but rc4 works for me on de.

**Comment by kennetjuh** [comment]
> to use rc4 by default try to change crypt=False to crypt=True in core/xiaomi_cloud.py

I tried this quick fix, but for me it's not working. (could still be someting wrong on my end)

**Comment by wojciea** [comment]
> > to use rc4 by default try to change crypt=False to crypt=True in core/xiaomi_cloud.py
> 
> Does it work for you ?

Changing 
```diff
-    def request_miot_api(self, api, data, method='POST', crypt=False, debug=True, **kwargs):
+    def request_miot_api(self, api, data, method='POST', crypt=True, debug=True, **kwargs):
        params = {}
```
does NOT solve the issue.
I can see 
```python
def request_rc4_api
```
being used (added some logging there)
But still get the `Got xiaomi cloud devices for %s failed: {'code': 0, 'message': 'auth err'}` from `def get_device_list`

**Comment by rezmus** [comment]
@al-one it is php i use to talk to cloud. i can send some samples with encrypted/decrypted data if needed.

```
function rc4($key, $str) {
	$s = array();
	for ($i = 0; $i < 256; $i++) {
		$s[$i] = $i;
	}
	$j = 0;
	for ($i = 0; $i < 256; $i++) {
		$j = ($j + $s[$i] + ord($key[$i % strlen($key)])) % 256;
		$x = $s[$i];
		$s[$i] = $s[$j];
		$s[$j] = $x;
	}
	$i = 0;
	$j = 0;
	$res = '';
	
	for ($k = 0; $k < 1024; $k++) {
		$i = ($i + 1) % 256;
		$j = ($j + $s[$i]) % 256;
		$x = $s[$i];
		$s[$i] = $s[$j];
		$s[$j] = $x;
	}
	
	for ($y = 0; $y < strlen($str); $y++) {
		$i = ($i + 1) % 256;
		$j = ($j + $s[$i]) % 256;
		$x = $s[$i];
		$s[$i] = $s[$j];
		$s[$j] = $x;
		$res .= $str[$y] ^ chr($s[($s[$i] + $s[$j]) % 256]);
	}
	return $res;
}

(...)

$path = "/home/device_list";
$method = "POST";
$data = '{}';

$key = base64_encode(hash('sha256', base64_decode($ssecurity) . base64_decode($nonce),true));
$sigstr = $method . '&' . $path . '&data=' . $data . '&' . $key;
$rc4sha = base64_encode(hex2bin(sha1($sigstr)));
$dataenc = base64_encode(rc4(base64_decode($key),$data));
$rc4hash = base64_encode(hex2bin(substr(bin2hex(rc4(base64_decode($key),$data . $rc4sha)), -2*(strlen($rc4sha)))));
$sigstr = $method . '&' . $path . '&data=' . $dataenc . '&rc4_hash__=' . $rc4hash . '&' . $key;
$sig = base64_encode(hex2bin(sha1($sigstr)));
$send = 'data=' . urlencode($dataenc) . '&rc4_hash__=' . urlencode($rc4hash) . '&signature=' . urlencode($sig) . '&_nonce=' . urlencode($nonce) .  '&ssecurity=' . urlencode($ssecurity);

(...)

$result = rc4(base64_decode($key),base64_decode($result));
```

**Comment by Wh1terat** [comment]
Should move to the new device list endpoint too now rc4 is enforced (/app/v2/home/device_list_page)

**Comment by Wh1terat** [comment]
@rezmus , @al-one 
I made this mitm script to make everyone's lives much easier.

It's got to catch the ssecurity token from serviceLoginAuth2 to work, or you can set it yourself.

```python
from typing import Optional

from mitmproxy import contentviews, flow, http, ctx

from base64 import b64decode, b64encode
import hashlib
import json

ssecurity = None

class RC4:
    _idx = 0
    _jdx = 0
    _ksa: list

    def __init__(self, pwd):
        self.init_key(pwd)

    def init_key(self, pwd):
        cnt = len(pwd)
        ksa = list(range(256))
        j = 0
        for i in range(256):
            j = (j + ksa[i] + pwd[i % cnt]) & 255
            ksa[i], ksa[j] = ksa[j], ksa[i]
        self._ksa = ksa
        self._idx = 0
        self._jdx = 0
        return self

    def crypt(self, data):
        if isinstance(data, str):
            data = data.encode()
        ksa = self._ksa
        i = self._idx
        j = self._jdx
        out = []
        for byt in data:
            i = (i + 1) & 255
            j = (j + ksa[i]) & 255
            ksa[i], ksa[j] = ksa[j], ksa[i]
            out.append(byt ^ ksa[(ksa[i] + ksa[j]) & 255])
        self._idx = i
        self._jdx = j
        self._ksa = ksa
        return bytearray(out)

    def init1024(self):
        self.crypt(bytes(1024))
        return self


def create_key(ssecurity, nonce):
    return b64encode(hashlib.sha256(b64decode(ssecurity) + b64decode(nonce)).digest())


def response(flow: flow.Flow):
    if flow.request.path == "/pass/serviceLoginAuth2":
        if "ssecurity" in flow.response.text:
            resjs = json.loads(flow.response.text.replace("&&&START&&&", ""))
            global ssecurity
            ssecurity = resjs["ssecurity"]
            ctx.log(f"miotrc4 - ssecurity token: {ssecurity}")


class ViewMiOTRC4(contentviews.View):
    name = "miotrc4"

    @staticmethod
    def decrypt_data(pwd, data):
        return RC4(b64decode(pwd)).init1024().crypt(b64decode(data)).decode('utf-8')

    def __call__(
        self,
        data: bytes,
        *,
        content_type: Optional[str] = None,
        flow: Optional[flow.Flow] = None,
        http_message: Optional[http.Message] = None,
        **unknown_metadata,
    ) -> contentviews.TViewResult:
        global ssecurity
        if ssecurity:
            if "miot-encrypt-algorithm" in flow.request.headers:
                enctype = flow.request.headers["miot-encrypt-algorithm"]
                ctx.log(f"{self.name} - miot-encrypt-algorithm: {enctype}")
                if enctype == "ENCRYPT-RC4":
                    nonce = flow.request.urlencoded_form.get("_nonce", None).encode()
                    if nonce:
                        key = create_key(ssecurity, nonce)
                        ctx.log(f"{self.name} - Key: {key}, Nonce: {nonce}")
                        if isinstance(http_message, http.Request):
                            data = flow.request.urlencoded_form.get(
                                "data", data
                            ).encode()
                            ctx.log(f"{self.name} - [REQ] data: {data}")
                            decoded_data = self.decrypt_data(key, data)
                            ctx.log(f"{self.name} - [REQ] decoded_data: {decoded_data}")
                            form_data = flow.request.urlencoded_form
                            pretty = json.dumps(
                                json.loads(decoded_data), indent=4, sort_keys=True
                            )
                            form_data["data (decrypted)"] = "\n" + pretty
                            return self.name, list(
                                contentviews.base.format_dict(form_data)
                            )
                        elif isinstance(http_message, http.Response):
                            ctx.log(f"{self.name} - [RES] data: {data}")
                            decoded_data = self.decrypt_data(key, data)
                            ctx.log(f"{self.name} - [RES] decoded_data: {decoded_data}")
                            pretty = json.dumps(
                                json.loads(decoded_data), indent=4, sort_keys=True
                            )
                            return self.name, list(
                                contentviews.base.format_text(pretty)
                            )
                else:
                    ctx.log(f"{self.name} - Unknown miot-encrypt-algorithm ({enctype})")
        return "Raw", contentviews.format_text(data)

    def render_priority(
        self,
        data: bytes,
        *,
        content_type: Optional[str] = None,
        flow: Optional[flow.Flow] = None,
        **unknown_metadata,
    ) -> float:
        global ssecurity
        if ssecurity:
            if "miot-encrypt-algorithm" in flow.request.headers:
                if flow.request.headers["miot-encrypt-algorithm"] == "ENCRYPT-RC4":
                    return 1
        return 0


view = ViewMiOTRC4()


def load(l):
    contentviews.add(view)


def done():
    contentviews.remove(view)
```

**Comment by Jo-Jo1987** [comment]
Currently facing the same issues with also the integration of Xiaomi Gateway 3. So i assume the issue is at the DE servers itself.
I am also using Xiaomi MIOT auto and i cannot renew anything and it does also not show my current working devices up and running. I tried the workaround with the RC4 to set crypt false but it did not fix anything at all.

**Comment by urukalo** [comment]
here is a solution used on the token extractor

https://github.com/PiotrMachowski/Xiaomi-cloud-tokens-extractor/commit/0e98bcae9aef525a7945e8c6a41df2c4e2d54ba5

**Comment by al-one** [comment]
Thanks! I have fixed the bug in the latest [commit](https://github.com/al-one/hass-xiaomi-miot/commit/e0d8d6bc53b1fec07c8e4da51497583ee9b0dd04) of branch [v0.4.x](https://github.com/al-one/hass-xiaomi-miot/tree/v0.4.x). Please urgrade and try. If it works, I will publish the version and merge it into the main branch.

**Comment by RPSouto** [comment]
Tested and everything seems to work just fine! Amazing!

**Comment by kennetjuh** [comment]
> Thanks! I have fixed the bug in the latest [commit](https://github.com/al-one/hass-xiaomi-miot/commit/e0d8d6bc53b1fec07c8e4da51497583ee9b0dd04) of branch [v0.4.x](https://github.com/al-one/hass-xiaomi-miot/tree/v0.4.x). Please urgrade and try. If it works, I will publish the version and merge it into the master branch.
> 
> To upgrade to latest commit of v0.4.x:
> 
> ```shell
> wget -q -O - https://cdn.jsdelivr.net/gh/al-one/hass-xiaomi-miot/install.sh | ARCHIVE_TAG=v0.4.x bash -
> ```

This fix works perfect for me. thanks for your effort!!!

**Comment by pkejval** [comment]
I can confirm that fix in https://github.com/al-one/hass-xiaomi-miot/issues/345#issuecomment-1003857714 is working! Thank you!

**Comment by sdimitrov-sms** [comment]
Working for me as well!

**Comment by kodifan** [comment]
fix is working like a charm. thx :)

**Comment by Jo-Jo1987** [comment]
works fine again!

**Comment by alimek** [comment]
works for me too 👍  💯

**Comment by Jo-Jo1987** [comment]
Hi,
It looks fixed at first sight!
But, i do have a bootup time from Home assistant which needed 149 seconds!

Yesterday i faced issues all over the place with Xiaomi cloud DE servers.
Now this has been fixed in Xiaomi miot auto and as well in your xiaomi cloud map extractor.

I use a roborock S7 , but after all the updates. I lost my map and it does not start up correct
Also my home assistant keeps starting , and waiting on something right now and became very slow
xiaomi_miot:
  username: 
  password: 
camera:
  - platform: xiaomi_cloud_map_extractor
    host: 
    token: 
    username:
    password: 
    draw: ['all']
    attributes:
      - calibration_points
   
Using above settings in my config.yaml

All things working according in Xiaomi , except my robot. And as well , the booting time takes more than 140 seconds right now. So i guess, it is not completely fixed yet.

**Comment by mentalloflex** [comment]
I'm afraid I still get the error with the DE server. Have tried reinstalling the integration but to no avail. What could I be doing wrong?

**Comment by sdimitrov-sms** [comment]
@mentalloflex the fix is not official yet, so you have to update manually, as it was explained earlier in the thread. When @al-one makes it official and pushes it to master, only then reinstalling will fix the issue OOTB.

**Comment by mentalloflex** [comment]
Got it! Thank you!

**Comment by No-Smart** [comment]
Manual FIX Work **OK**!!!!!!!!  Fantastic 

wget -q -O - https://cdn.jsdelivr.net/gh/al-one/hass-xiaomi-miot/install.sh | ARCHIVE_TAG=v0.4.x bash -

**Comment by raptr55** [comment]
> Hi, It looks fixed at first sight! But, i do have a bootup time from Home assistant which needed 149 seconds!
> 
> Yesterday i faced issues all over the place with Xiaomi cloud DE servers. Now this has been fixed in Xiaomi miot auto and as well in the xiaomi cloud map extractor.
> 
> I use a roborock S7 , but after all the updates. I lost my map and it does not start up correct Also my home assistant keeps starting , and waiting on something right now and became very slow xiaomi_miot: username: password: camera:
> 
> * platform: xiaomi_cloud_map_extractor
>   host:
>   token:
>   username:
>   password:
>   draw: ['all']
>   attributes:
>   
>   * calibration_points
> 
> Using above settings in my config.yaml
> 
> All things working according in Xiaomi , except my robot. And as well , the booting time takes more than 140 seconds right now. So i guess, it is not completely fixed yet.

You have closed this bug in the other thread.

@al-one could you kindly merge this fix info the master branch?

**Comment by Zeunas** [comment]
Same 😃

**Comment by kimme1024** [comment]
Tried upgrading on MacOS but still can't login into integration (unknown error occured)

**Comment by balbulator** [comment]
Tell me, maybe I'm doing something wrong, but this is what I get in the terminal
![1](https://user-images.githubusercontent.com/61936199/147940103-5523664f-792b-467b-8b46-98fd9285696a.jpg)

**Comment by Jo-Jo1987** [comment]
you miss the wget in the front. don't copy paste. Please type it in.

**Comment by szymonmal** [comment]
@balbulator I think it's spaces after ARCHIVE_TAG and equals sign, please remove them and try again. 
Change `ARCHIVE_TAG = v0.4.x` to `ARCHIVE_TAG=v0.4.x`

Copy paste from al-one post should also work:

`wget -q -O - https://cdn.jsdelivr.net/gh/al-one/hass-xiaomi-miot/install.sh | ARCHIVE_TAG=v0.4.x bash -`

**Comment by balbulator** [comment]
Thanks! Everything works as before!

**Comment by kimme1024** [comment]
Hi, 

I tried 

```
wget -q -O - https://cdn.jsdelivr.net/gh/al-one/hass-xiaomi-miot/install.sh | ARCHIVE_TAG=v0.4.x bash -
```

This installs the component as it should.

However I still can't connect to miio with this as a log:

```
Logger: aiohttp.server
Source: components/xiaomi_miio/config_flow.py:250 
First occurred: 16:52:36 (1 occurrences) 
Last logged: 16:52:36

Error handling request
Traceback (most recent call last):
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/forwarded.py", line 98, in forwarded_middleware
    return await handler(request)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/homeassistant/components/config/config_entries.py", line 157, in post
    return await super().post(request, flow_id)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 252, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/homeassistant/data_entry_flow.py", line 325, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/homeassistant/components/xiaomi_miio/config_flow.py", line 250, in async_step_cloud
    devices_raw = await self.hass.async_add_executor_job(
  File "/opt/homebrew/Cellar/python@3.9/3.9.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/kimheymans/Documents/homeassistant/lib/python3.9/site-packages/micloud/micloud.py", line 251, in get_devices
    return json_resp['result']['list']
KeyError: 'result'
```

I'm running Monterey on an M1 mini.

Thanks in advance!

**Comment by al-one** [comment]
@kimme1024 `xiaomi_miio` is not this custom component.

**Comment by Wh1terat** [comment]
With https://github.com/al-one/hass-xiaomi-miot/commit/6ef3e24b9f3742b586135c0371efad9b27ae1a34 being merged, I'm going to close this issue now.

Thanks @al-one 😄

**Comment by balbulator** [comment]
An update has come, thanks to the author
