### ISSUE TITLE
`entity_category` not applied to entity

### ISSUE THREAD

**Issue by blakadder** [al-one/hass-xiaomi-miot#960]
Editing device_customizes.py I've tried adding an `entity_category` to certain entities but that field is never applied. The entity applies other attributes like `unit_of_measurement` or `device_class`

configurations tried:
```
    'viomi.vacuum.v18:clean_use_time': {
        'value_ratio': 0.0166667,
        'device_class': 'duration',
        'entity_category': 'diagnostic',
},
```
```
    'viomi.vacuum.v18:repeat_state': {
        'entity_category': 'config',
    },
```
neither `entity_category` config works

**Comment by al-one** [comment]
Fixed in master branch.

**Comment by blakadder** [comment]
Still does not happen for devices in device_customisations.py. I only get the battery percentage in the diagnostic group despite setting multiple entities in custom

**Comment by al-one** [comment]
Fixed in https://github.com/al-one/hass-xiaomi-miot/commit/582fd22519cc374401dd79f74d569e7c602e099c
